# pipelinerun.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: springboot-run
spec:
  pipelineRef:
    name: springboot-build-deploy
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: springboot-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repo-url
      value: https://github.com/YOUR_USERNAME/FoodRestaurant.git
    - name: image-url
      value: us-central1-docker.pkg.dev/positive-water-468219-g2/food-restaurant/app
