# PVC (needed for workspace)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# TaskRun: Git Clone
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: git-clone-taskrun
spec:
  taskRef:
    name: git-clone
    kind: ClusterTask
  params:
    - name: url
      value: https://github.com/nagasai06/FoodRestaurant.git
    - name: revision
      value: master
    - name: deleteExisting
      value: "true"
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: shared-workspace-pvc
  podTemplate:
    securityContext:
      fsGroup: 65532
---
# TaskRun: Maven Build
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: maven-build-taskrun
spec:
  taskSpec:
    workspaces:
      - name: source
    steps:
      - name: mvn-build
        image: maven:3.8.5-openjdk-17
        workingDir: $(workspaces.source.path)
        script: |
          mvn clean install
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: shared-workspace-pvc
