apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: kaniko-build-push-taskrun
spec:
  taskRef:
    name: kaniko-build-push
  params:
    - name: IMAGE
      value: <<Google Cloud Artifact Repository Image URL>>
    - name: DOCKERFILE
      value: Dockerfile
    - name: CONTEXT
      value: .
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: shared-workspace-pvc
