apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko-build-push
spec:
  params:
    - name: IMAGE
      type: string
      description: The image name to push to
    - name: DOCKERFILE
      type: string
      default: Dockerfile
      description: Path to the Dockerfile relative to the context
    - name: CONTEXT
      type: string
      default: .
      description: The build context path
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/kaniko-secret.json
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret
      args:
        - "--dockerfile=$(workspaces.source.path)/$(params.DOCKERFILE)"
        - "--context=$(workspaces.source.path)/$(params.CONTEXT)"
        - "--destination=$(params.IMAGE)"
        - "--verbosity=debug"
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
