apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-build
spec:
  workspaces:
    - name: source
  steps:
    - name: mvn-package
      image: maven:3.8.4-openjdk-17
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        mvn clean package -DskipTests
