apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-restaurant
  labels:
    app: food-restaurant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-restaurant
  template:
    metadata:
      labels:
        app: food-restaurant
    spec:
      containers:
      - name: food-restaurant
        image: us-central1-docker.pkg.dev/positive-water-468219-g2/food-restaurant/app:latest
        ports:
        - containerPort: 8080
